name: flutter_application_activity_record
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  pinput: ^4.0.0
  qr_flutter: ^4.1.0
  flip_card: ^0.7.0
  intl: ^0.19.0
  mobile_scanner: ^3.5.0
  http: ^1.1.0
  calendar_date_picker2: ^2.0.1
  salomon_bottom_bar: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/login_ellipse.png
    - assets/images/card_background.png
    - assets/images/card_background_oganize.png
    - assets/images/bgcredit.jpg
    - assets/animations/
    - assets/fonts/
fonts:
  - family: Prompt
    fonts:
      - asset: assets/fonts/Prompt-Regular.ttf
      - asset: assets/fonts/Prompt-Medium.ttf
        weight: 500
      - asset: assets/fonts/Prompt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Prompt-Bold.ttf
        weight: 700
      - asset: assets/fonts/Prompt-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Prompt-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Prompt-Light.ttf
        weight: 300

  - family: Kanit
    fonts:
      - asset: assets/fonts/Kanit-Regular.ttf
      - asset: assets/fonts/Kanit-Medium.ttf
        weight: 500
      - asset: assets/fonts/Kanit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Kanit-Bold.ttf
        weight: 700